defaults:
  - lewm_masked_action_nce
  - _self_

output_model_name: lewm_masked_action_state_nce

loss:
  masked:
    state_nce:
      weight: 0.03
      mode: delta
      temperature: 0.1

wandb:
  config:
    project: masked-transition-lewm
    name: ${output_model_name}
