defaults:
  - lewm_masked
  - _self_

output_model_name: lewm_masked_vicreg

loss:
  variance_reg:
    weight: 0.05
    gamma: 0.1

wandb:
  config:
    project: masked-transition-lewm
    name: ${output_model_name}
